apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIxMTIxMjE2MTcxN1oXDTMxMTIxMTE2MTcxN1owFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALL1
    epf/8Yph/Dk13RxRqoPmXRxrBczsyGL6vZyMbEo+VXuHzO0oEO/vGlJx9bR73+qv
    SuUNDoHsJhc/47rhIs++ZYnvn77bzOvQ+iboEyj7aU9LHN/ECz7dKTAzfftQRIhH
    p5Q+GChel5qbmuKx/PcH7bCp3NtyUZPMllx+xplu1ooM9ZctG7M0+UewFSjJjyhb
    MJoj47yfYdfTNHk8mX7qhxTyzQWyw/pAYRKDdYg84nEg6vbcoN0rl8ImFYg0J6gI
    KrweGUsF/BnwSNtVUhQtK+zA9MM8Hs4JQREhI6Kbm+AXPAa+EHV2CGaAlMscDzSO
    jDsUN+8pjgRT138CPOcCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQOb+7lbO3nmfTPpPkH8R6qkMwYbTANBgkqhkiG9w0BAQsFAAOCAQEAj7Bcx7Hn
    Me5LDN7BkQ7MyHgZe9Ed1ZpNcHZmQIfLJ/48be5k2ovaXcRGCVkjZ4M+p8aFHool
    DW4byyhhf7gQOT0UC8JEiHGt+aNTOF6AOe72ee6P8TXLiZWGWLgxQb9yxYXHb39E
    xR58FG+jCozn5r8hcDlymdK/BktZ2meGBhs1lj9xVlsil3jiFJkF6DhEZdhvk+K6
    5juEZi6QEMJG/Di1/204LQhIgpY+16jOgg0OQa9K33MXHbRSF/hmxod6Lq0IxbqV
    6BAsQ5jUwFPcWtwthcLxEKidTs52/z5g9a8z4g+QYYid9qdiTBieWjsH/tZhf7MH
    /B3c/yGfUxfjhA==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-12-13T16:40:12Z"
  name: kube-root-ca.crt
  namespace: guestbook
